### ISSUE TITLE
bgp example

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-protocol-maintenance#10]
BGP used to be very strict.  After some collaboration (maintenance), the community found a few ways in which leniency could be specified, making the protocol better.

**Comment by DavidSchinazi** [comment]
Do you know if this BGP history is documented somewhere?

**Comment by martinthomson** [comment]
No idea, which is why this issue remains unaddressed :)  I was going to close it if nothing turned up.

**Comment by DavidSchinazi** [comment]
Closing SGTM, it sounds like a good example but the amount of archeology required would be significant.

**Comment by martinthomson** [comment]
Yeah, let's do that.
