### ISSUE TITLE
be explicit about software development model assumptions

### ISSUE THREAD

**Issue by britram** [intarchboard/draft-protocol-maintenance#13]
quoting myself from email:

> This document has always very clearly had a specific set of development and deployment properties in mind.
> One of these properties is that there is an effective communications path with short turnaround time between those responsible for operating a protocol (for a fuzzy value of "operating") and those responsible for implementing it. Another is that failures in the protocol are observable and actionable, whether by the operators or the implementors.

Being explicit about this (preferably without saying "DevOps" would be useful in scoping the document.

**Comment by martinthomson** [comment]
I think that text for #11 added in recent versions will suffice.

> Maintenance is most effective if it is responsive, which is greatly affected by
how rapidly protocol changes can be deployed.  For protocol deployments that
operate on longer time scales, temporary workarounds following the spirit of the
robustness principle might be necessary.  If specifications can be updated more
readily than deployments, details of the workaround can be documented, including
the desired form of the protocols once the need for workarounds no longer exists
and plans for removing the workaround.

This is not specifically about a particular deployment model, though it is certainly informed by the advantages of a shorter feedback loop.  I was just investigating the EDNS compatibility mess and it seems like that worked well enough...over a 20 year period.  The protocol was defined in 1999, the workaround was documented in 2013, and removed from many deployments in 2019.  We might hope for a shorter cycle than that, but it worked just as described.
