### ISSUE TITLE
time and experience reference

### ISSUE THREAD

**Issue by hardaker** [intarchboard/draft-protocol-maintenance#65]
> Time and experience shows that negative consequences to interoperability
> accumulate over time if implementations silently accept faulty input.

This may be true, but is a generic statement without facts or
references behind it.

**Comment by martinthomson** [comment]
The document provides the evidence. In multiple places.  I'm OK with this, even if it does stick out a little.

**Comment by hardaker** [comment]
You could state that more clearly, or [of course] just ignore this suggestion.  Maybe:

This documents outlines what time and experience has shown to be negative consequences to interoperability that can accumulate over time if implementations silently accept faulty input.

**Comment by DavidSchinazi** [comment]
Given that this is in the introduction, I don't think we need to forward reference the justification for our opening statement when the entire document is roughly justification. I'd prefer to close with no action.
