### ISSUE TITLE
better example than HTML?

### ISSUE THREAD

**Issue by hardaker** [intarchboard/draft-protocol-maintenance#66]
> Where input is provided by users, allowing flexibility might serve to make the
  > protocol more accessible, especially for non-expert users. HTML authoring
  > {{HTML}} is an example of this sort of design.

  The problem with this example is that HTML is not an IETF protocol.
  Could we find a better example within the IETF specifications?
  Maybe SMTP headers?  or HTTP headers?

**Comment by DavidSchinazi** [comment]
I don't think SMTP or HTTP headers are a good example - malformed HTTP headers cause faults whereas invalid HTML is accepted in a best guess fashion. I don't think using an example outside of IETF is a problem.

**Comment by martinthomson** [comment]
Yeah, SMTP and HTTP are great examples of the natural extension of the "let's build a protocol that can take any old garbage" principle.  That's a principle (sic) that is sometimes mistaken for the Robustness Principle and rarely an applicable one.  HTML is a justifiable example.  Though maybe the XHTML crowd will disagree, they lost for a good set of reasons.
