### ISSUE TITLE
Citation Needed: RFC 3117, On the Design of Application Protocols

### ISSUE THREAD

**Issue by jhwoodyatt** [intarchboard/draft-protocol-maintenance#73]
It would be an oversight if this draft contained no acknowledgement of a much earlier contribution to this subject in [RFC 3117](https://www.rfc-editor.org/rfc/rfc3117) "On the Design of Application Protocols" by Marshall Rose.

Section 4.5 "Robustness" contains the following observation:

>    A well-designed protocol is robust.
> 
>    Robustness and efficiency are often at odds.  For example, although
>    defaults are useful to reduce packet sizes and processing time, they
>    tend to encourage implementation errors.
> 
>    Counter-intuitively, Postel's robustness principle ("be conservative
>    in what you send, liberal in what you accept") often leads to
>    deployment problems.  Why? When a new implementation is initially
>    fielded, it is likely that it will encounter only a subset of
>    existing implementations.  If those implementations follow the
>    robustness principle, then errors in the new implementation will
>    likely go undetected.  The new implementation then sees some, but not
>    widespread deployment.  This process repeats for several new
>    implementations.  Eventually, the not-quite-correct implementations
>    run into other implementations that are less liberal than the initial
>    set of implementations.  The reader should be able to figure out what
>    happens next.
> 
>    Accordingly, explicit consistency checks in a protocol are very
>    useful, even if they impose implementation overhead.

I once heard Mr. Rose concisely describe this in an informal hallway conversation with a slight modification of Postel's slogan:

> Be conservative in what you send, but not *too* conservative, and be liberal in what you receive, but not *too* liberal.

I'm happy to see that IAB is finally considering the wisdom of this observation, which has been lying mostly unconsidered for more than twenty years in an obscure RFC that has never been referenced anywhere. I hope the draft will be published without much further delay.

**Comment by DavidSchinazi** [comment]
Hi @jhwoodyatt long time no see! Wow I had never heard of RFC 3117 personally. I'm amused by how closely its ideas match what we're saying here, down to using the work "robust". I've written up PR #75 to add this to the acknowledgements.

**Comment by jhwoodyatt** [comment]
I'm grateful. I've always thought that little bit in the BXXP draft was an important observation.
