### ISSUE TITLE
RjS has some experience with broken test suites

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-protocol-maintenance#8]
These can cause a lot of problems.

**Comment by DavidSchinazi** [comment]
Can you elaborate on this issue? Is the idea that conformance test suites need to pass with major deployments in order to be useful?

**Comment by martinthomson** [comment]
Apparently sipit turned out a lot of interop issues that were traced to bad conformance suites.

I'm not sure how useful that is with respect to the central theme of this work though.  It's related, but then everything is at some level.  This ends up being part of the overall way in which implementations might diverge.  Test suites can be a unifying force in the same way that specifications can, but only if they are either universally used or consistent with good specifications.  In the former case, the test suite can supplant the specification.

In any case, I'm inclined to let this issue close without action.

**Comment by DavidSchinazi** [comment]
Thanks for clarifying. Closing without action SGTM.
