### ISSUE TITLE
equilibrium points

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-protocol-maintenance#9]
The equilibria thing that ekr raised on the list has hit a nerve.  The document should address that and make the point that the protocol lifecycle has different points in the strictness-postel continuum.  Related to this, the stasis point for different implementations might depend on their relative market position.

**Comment by DavidSchinazi** [comment]
It took some archeology but I found [the mailing post mentioned in this issue](https://mailarchive.ietf.org/arch/msg/ietf/b75_SVgpObx_-WKkRwhZnzKOdJk/):
> There seem to be two main equilibria:
>
> 1. There's a critical mass of very strict implementations; in this case it's very hard for a non-conformant implementation to enter the ecosystem.
> 2. There's a critical mass of non-conformant implementations; in this case it's very hard for a strict implementation to enter the ecosystem.
>
> Once you're in one equilibrium or the other, it's very hard to get out.
